#!/usr/bin/env python
"""Bmad/Tao worker for the lattix ``bmad`` oracle.

Runs *inside* the Bmad conda environment (Python 3.13 / numpy 2 / pytao 1.2.4)
and therefore imports nothing from lattix — only the standard library, numpy
and pytao.  ``lattix.oracles.pytao`` launches it as a subprocess by file path
(or calls :func:`run` in-process when pytao is importable) and reads the JSON it
writes::

    python bmad_worker.py DECK --out result.json \\
        [--species proton --kinetic-ev 2.1e6] \\
        [--betx 10 --alfx 0 --bety 10 --alfy 0 --dx 0 --dpx 0 --dy 0 --dpy 0] \\
        [--probe probe.npy] [--workdir DIR]

How the lattice is driven
-------------------------
A *wrapper* lattice is written into a fresh temporary directory — Bmad caches a
``.digested`` file next to the root lattice keyed on the file's 1-second
modification time, so re-using a wrapper path within the same second silently
loads the previous lattice (observed on 20260828-0).  The wrapper ``call``s the
user's deck by absolute path (Bmad resolves the deck's own relative ``call``s
against the deck's directory, verified) and *then* sets::

    parameter[geometry] = open
    parameter[particle] = <species>                     (only with --kinetic-ev)
    parameter[e_tot]    = mass_of(<species>) + <KE>     (only with --kinetic-ev)
    beginning[beta_a] ... beginning[etap_y]             (always)

*after* the call so that an explicit beam overrides whatever the deck set
(same rule as the cpymad oracle: explicit BeamSpec wins, otherwise the deck's
own ``parameter[e_tot]``/``p0c`` stands).  ``mass_of()`` is evaluated by Bmad,
so the requested kinetic energy is exact in Bmad's own mass convention
(m_p = 938 272 089.43 eV in Bmad vs 938 272 088.16 eV in lattix.SPECIES).
Species names: proton, electron, positron, deuteron, antiproton; ``h-`` is
written as ``#1H-`` (the H-1 atom with one extra electron; plain ``H-`` would
use the isotope-averaged hydrogen mass).

Observables (element exits; BEGINNING = index 0 is skipped, the auto-inserted
END marker is kept as a zero-length row): ``ele_mat6`` (rows '1'..'6'),
``ele_floor`` ('Reference' = X, Y, Z, theta, phi, psi), ``ele_twiss``
(beta_a, alpha_a, beta_b, alpha_b, eta_x, etap_x, eta_y, etap_y), ``lat_list``
for name, s, l, e_tot, p0c, key.  Matrices and Twiss are read *before* any probe
particle is launched: Tao computes ``mat6`` about the orbit started from
``particle_start``, so probing first would change them.

Native basis (x, px, y, py, z, pz): z ahead-positive, pz = Δp/p0 with p0 the
*local* reference momentum — lcavity changes it (p0-following engine).
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import tempfile
import traceback

# When run by file path, Python prepends this directory to sys.path and
# ``import pytao`` would resolve to lattix/oracles/pytao.py (the adapter) instead
# of the real package.  Drop it before importing anything third-party.
_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path[:] = [p for p in sys.path if os.path.abspath(p or os.getcwd()) != _HERE]

import numpy as np  # noqa: E402

SPECIES_BMAD = {
    "proton": "proton", "antiproton": "antiproton", "electron": "electron",
    "positron": "positron", "deuteron": "deuteron", "h-": "#1H-",
}
_CHARGE_FALLBACK = {"proton": 1, "antiproton": -1, "electron": -1, "positron": 1,
                    "deuteron": 1, "h-": -1}
_TWISS_KEYS = (("betx", "beta_a"), ("alfx", "alpha_a"), ("bety", "beta_b"), ("alfy", "alpha_b"),
               ("dx", "eta_x"), ("dpx", "etap_x"), ("dy", "eta_y"), ("dpy", "etap_y"))
_ORBIT = ("x", "px", "y", "py", "z", "pz")
TAO_ARGS = "-noplot -noinit -nostartup"


def write_wrapper(deck: str, workdir: str, species: str | None, kinetic_ev: float | None,
                  twiss: dict[str, float]) -> str:
    lines = ["! generated by lattix.oracles.bmad_worker — do not edit",
             f'call, file = "{deck}"',
             "parameter[geometry] = open"]
    if kinetic_ev is not None:
        sp = SPECIES_BMAD.get((species or "proton").lower(), species)
        lines += [f"parameter[particle] = {sp}",
                  f"parameter[e_tot] = mass_of({sp}) + {float(kinetic_ev)!r}"]
    for attr, key in (("beta_a", "betx"), ("alpha_a", "alfx"), ("beta_b", "bety"),
                      ("alpha_b", "alfy"), ("eta_x", "dx"), ("etap_x", "dpx"),
                      ("eta_y", "dy"), ("etap_y", "dpy")):
        lines.append(f"beginning[{attr}] = {float(twiss[key])!r}")
    path = os.path.join(workdir, "lattix_wrapper.bmad")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path


def _mat6(tao, ix: int) -> list[list[float]]:
    m = tao.ele_mat6(ix)
    return [[float(v) for v in np.asarray(m[str(r)], dtype=float)] for r in range(1, 7)]


def run(deck: str, *, species: str | None = "proton", kinetic_ev: float | None = None,
        betx: float = 10.0, alfx: float = 0.0, bety: float = 10.0, alfy: float = 0.0,
        dx: float = 0.0, dpx: float = 0.0, dy: float = 0.0, dpy: float = 0.0,
        probe: str | None = None, workdir: str | None = None) -> dict:
    """Run Tao on *deck* and return the result dictionary (JSON-serialisable)."""
    import pytao
    from pytao import Tao

    deck = os.path.abspath(deck)
    if not os.path.isfile(deck):
        raise FileNotFoundError(deck)
    if workdir:
        os.makedirs(workdir, exist_ok=True)
    # fresh directory every run: never share a wrapper path (stale .digested, see module doc)
    rundir = tempfile.mkdtemp(prefix="lattix_bmad_", dir=workdir)
    warnings: list[str] = []
    if kinetic_ev is None and species not in (None, "proton"):
        warnings.append(f"--species {species} ignored: no --kinetic-ev given, so the deck's own "
                        f"particle/energy is used")
    wrapper = write_wrapper(deck, rundir, species, kinetic_ev,
                            {"betx": betx, "alfx": alfx, "bety": bety, "alfy": alfy,
                             "dx": dx, "dpx": dpx, "dy": dy, "dpy": dpy})
    cwd = os.getcwd()
    os.chdir(rundir)
    try:
        try:
            tao = Tao(f"-lat {wrapper} {TAO_ARGS}")
        except Exception as e:  # noqa: BLE001
            raise RuntimeError(f"Tao failed to load {deck} (wrapper {wrapper}): {e}") from e
        return _collect(tao, pytao, deck, wrapper, species, probe, warnings)
    finally:
        os.chdir(cwd)


def _collect(tao, pytao, deck: str, wrapper: str, species: str | None, probe: str | None,
             warnings: list[str]) -> dict:
    names = [str(x) for x in tao.lat_list("*", "ele.name")]
    ix = np.asarray(tao.lat_list("*", "ele.ix_ele"), dtype=int)
    n_all = len(names)
    if n_all < 2:
        raise RuntimeError(f"lattice has no tracking elements after BEGINNING: {names}")
    if not np.array_equal(ix, np.arange(n_all)):
        raise RuntimeError(f"unexpected element indexing from lat_list: {ix.tolist()}")
    s = np.asarray(tao.lat_list("*", "ele.s"), dtype=float)
    length = np.asarray(tao.lat_list("*", "ele.l"), dtype=float)
    e_tot = np.asarray(tao.lat_list("*", "ele.e_tot"), dtype=float)
    p0c = np.asarray(tao.lat_list("*", "ele.p0c"), dtype=float)
    keys = [str(x) for x in tao.lat_list("*", "ele.key")]

    # matrices / floor / twiss BEFORE any particle_start change (see module doc)
    mat6, floor = [], []
    twiss: dict[str, list[float]] = {k: [] for k, _ in _TWISS_KEYS}
    n_unreadable = 0
    for i in range(1, n_all):
        try:
            mat6.append(_mat6(tao, i))
        except Exception as e:  # noqa: BLE001 - Fortran prints an overflowed exponent as "2.77+100"
            raise RuntimeError(f"transfer matrix of element {i} ({names[i]}) unreadable ({e}): the line is "
                               "unstable at this reference — check the species and energy the deck was "
                               "written for") from None
        ref = np.asarray(tao.ele_floor(i, where="end")["Reference"], dtype=float)
        floor.append([float(ref[0]), float(ref[1]), float(ref[2]), float(ref[3])])
        try:
            tw = tao.ele_twiss(i)
        except Exception:  # noqa: BLE001 - Twiss beyond 1e100 (an unstable line): the maps still compare
            tw = {}
            n_unreadable += 1
        for k, bk in _TWISS_KEYS:
            twiss[k].append(float(tw[bk]) if bk in tw else float("nan"))
    if n_unreadable:
        warnings.append(f"Twiss parameters unreadable at {n_unreadable} element(s) (values beyond 1e100: the "
                        "line is unstable at this reference — check the species and energy the deck was "
                        "written for)")
    if all(math.isnan(v) for v in twiss["betx"]):
        warnings.append("ele_twiss returned no Twiss parameters (open line without a valid "
                        "beginning[...] setting?)")

    # reference species from Bmad itself (mass_of / charge_of in Bmad's own constants)
    sp_name = str(tao.ele_orbit(0).get("species", "")).strip()
    try:
        mass = float(np.asarray(tao.evaluate(f"mass_of({sp_name})"), dtype=float).ravel()[0])
        charge = float(np.asarray(tao.evaluate(f"charge_of({sp_name})"), dtype=float).ravel()[0])
    except Exception as e:  # noqa: BLE001
        mass = float(math.sqrt(max(e_tot[0] ** 2 - p0c[0] ** 2, 0.0)))
        charge = float(_CHARGE_FALLBACK.get((species or "").lower(), 1))
        warnings.append(f"mass_of/charge_of({sp_name!r}) failed ({e}); mass from "
                        f"sqrt(E_tot^2 - p0c^2), charge from the requested species")

    probe_out = None
    if probe is not None:
        probe_out = _track_probe(tao, np.load(probe), n_all - 1)

    try:
        version = str(tao.version())
    except Exception:  # noqa: BLE001
        version = None

    return {
        "deck": deck, "wrapper": wrapper, "species": sp_name,
        "names": names[1:], "keys": keys[1:],
        "s_out": s[1:].tolist(), "length": length[1:].tolist(),
        "mat6": mat6,
        "e_tot_in": e_tot[:-1].tolist(), "e_tot_out": e_tot[1:].tolist(),
        "p0c_in": p0c[:-1].tolist(), "p0c_out": p0c[1:].tolist(),
        "mass_ev": mass, "charge": charge,
        "floor": floor, "twiss": twiss, "probe_out": probe_out,
        "warnings": warnings, "tao_version": version,
        "pytao_version": getattr(pytao, "__version__", None), "python": sys.executable,
        "numpy_version": np.__version__,
    }


def _track_probe(tao, coords: np.ndarray, last: int) -> list:
    coords = np.asarray(coords, dtype=float)
    if coords.ndim != 2 or coords.shape[1] != 6:
        raise ValueError(f"probe must be (N, 6), got {coords.shape}")
    out = np.full(coords.shape, np.nan)
    for j, row in enumerate(coords):
        if not np.all(np.isfinite(row)):
            continue
        for k, name in enumerate(_ORBIT):
            tao.cmd(f"set particle_start {name} = {float(row[k])!r}")
        try:
            o = tao.ele_orbit(last)
        except Exception:  # noqa: BLE001 -- lost particle: Tao complains, row stays NaN
            continue
        if str(o.get("state", "")).strip().lower() == "alive":
            out[j] = [float(o[k]) for k in _ORBIT]
    for name in _ORBIT:  # restore the reference orbit
        tao.cmd(f"set particle_start {name} = 0")
    return out.tolist()


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("deck")
    ap.add_argument("--out", help="write the result JSON here (default: stdout)")
    ap.add_argument("--species", default="proton")
    ap.add_argument("--kinetic-ev", type=float, default=None,
                    help="reference kinetic energy [eV]; omit to keep the deck's own energy")
    for k, v in (("betx", 10.0), ("alfx", 0.0), ("bety", 10.0), ("alfy", 0.0),
                 ("dx", 0.0), ("dpx", 0.0), ("dy", 0.0), ("dpy", 0.0)):
        ap.add_argument(f"--{k}", type=float, default=v)
    ap.add_argument("--probe", default=None, help="(N,6) .npy in Bmad coordinates")
    ap.add_argument("--workdir", default=None)
    a = ap.parse_args(argv)
    try:
        res = run(a.deck, species=a.species, kinetic_ev=a.kinetic_ev, betx=a.betx, alfx=a.alfx,
                  bety=a.bety, alfy=a.alfy, dx=a.dx, dpx=a.dpx, dy=a.dy, dpy=a.dpy,
                  probe=a.probe, workdir=a.workdir)
    except Exception:  # noqa: BLE001
        traceback.print_exc(file=sys.stderr)
        return 1
    text = json.dumps(res)
    if a.out:
        with open(a.out, "w") as f:
            f.write(text)
    else:
        sys.stdout.write(text + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
