"""Bmad reader tests (PLAN §6 task 2.2).

Inline decks cover every element class, the expression/variable machinery, ``call``,
element templates and ``name[attr]`` overrides, nested lines with reflection and
repetition, superposition, species/energy and both fidelity regimes.  Two real
decks are read as well: ``tests/data/public/helix/fodo.bmad`` (generated by Bmad's
own ``madx_to_bmad.py``, vendored) and — only when the clone is present, never
vendored, since ``bmad/Copyright`` is GPL-3 — Bmad's own
``regression_tests/write_foreign_test/write_foreign_test.bmad``.
"""
from __future__ import annotations

import math
from pathlib import Path

import pytest

from lattix.fidelity import TranslationError
from lattix.formats.bmad import Reader
from lattix.formats.bmad.reader import logical_lines, split_statements, split_top, strip_comment
from lattix.ir.elements import (
    Bend,
    Collimator,
    Directive,
    Drift,
    FieldMap,
    Foil,
    Instrument,
    Kicker,
    Marker,
    Multipole,
    Octupole,
    Patch,
    Quadrupole,
    RFCavity,
    Sextupole,
    Solenoid,
    Taylor,
)
from lattix.ir.walk import propagate

DATA = Path(__file__).resolve().parents[1] / "data" / "public" / "helix"
BMAD_CLONE = Path("/Users/abhishekpathak/Desktop/Projects/particle_tracking_codes/"
                  "tier3_peers/bmad-ecosystem")
FOREIGN = BMAD_CLONE / "regression_tests" / "write_foreign_test" / "write_foreign_test.bmad"

HEADER = """
parameter[particle] = proton
parameter[e_tot] = 1738272000
parameter[geometry] = open
"""


def read_text(tmp_path: Path, body: str, name: str = "deck.bmad", **kw):
    p = tmp_path / name
    p.write_text(HEADER + body)
    return Reader().read(p, **kw)


def brho(lat) -> float:
    return lat.reference.brho_signed


# ---------------------------------------------------------------- lexer
def test_strip_comment_honours_quotes():
    assert strip_comment('a: foil, material_type = "C!u" ! trailing') == \
        'a: foil, material_type = "C!u" '
    assert strip_comment("! whole line") == ""


def test_logical_lines_join_continuations():
    text = ("a: quadrupole, l = 1,\n   k1 = 2\n"          # trailing comma
            "b: drift, l = &\n  3\n"                       # ampersand
            "c: line = (a,\n   b)\n"                       # open bracket
            "d: drift, l = 4\n   , tilt = 0.1\n")          # begin-line comma
    got = [t for t, _ in logical_lines(text)]
    assert got == ["a: quadrupole, l = 1, k1 = 2", "b: drift, l = 3",
                   "c: line = (a, b)", "d: drift, l = 4 , tilt = 0.1"]


def test_split_statements_and_top_level():
    assert split_statements("a: drift, l=1; b: marker") == ["a: drift, l=1", "b: marker"]
    assert split_top("l = 1, grid = {a, b}, t = 2") == ["l = 1", "grid = {a, b}", "t = 2"]
    # a semicolon inside a quoted string is not a separator
    assert split_statements('a: foil, material_type = "C;u"') == ['a: foil, material_type = "C;u"']


# ---------------------------------------------------------------- basics
def test_fodo_public_deck_matches_the_madx_source():
    lat, rep = Reader().read(DATA / "fodo.bmad")
    assert lat.use == "fodo"
    assert lat.reference.species.name == "proton"
    assert lat.reference.kinetic_energy_eV == pytest.approx(1.738272e9 - 938_272_088.16)
    assert lat.total_length == pytest.approx(6.6)
    assert lat.meta["bmad_title"] == "HELIX MAD-X demo - FODO cell"
    assert {k: v.value for k, v in lat.variables.items()} == {
        "lquad": 0.3, "kfocus": 0.6, "lbend": 1.0, "abend": 0.1, "ehalf": 0.05}
    qf = lat.elements["qf"]
    assert isinstance(qf, Quadrupole)
    assert qf.multipole.Bn[1] == pytest.approx(0.6 * brho(lat))
    assert qf.expressions["multipole.Bn[1]"].text == "kfocus"
    b1 = lat.elements["b1"]
    assert (b1.bend.angle, b1.bend.e1, b1.bend.e2) == pytest.approx((0.1, 0.05, 0.05))
    assert rep.counts == {"EXACT": 9}


def test_species_and_energy_sources(tmp_path):
    lat, _ = read_text(tmp_path, "d: drift, l=1\nl1: line = (d)\nuse, l1\n")
    assert lat.reference.species.name == "proton"

    p = tmp_path / "p0c.bmad"
    p.write_text("parameter[particle] = #1H-\nparameter[p0c] = 1e9\n"
                 "d: drift, l=1\nl1: line = (d)\nuse, l1\n")
    lat, _ = Reader().read(p)
    assert lat.reference.species.name == "h-"
    assert lat.reference.pc_eV == pytest.approx(1e9)

    # Bmad's own default reference species is POSITRON (measured with Tao)
    p = tmp_path / "def.bmad"
    p.write_text("parameter[e_tot] = 1e6\nd: drift, l=1\nl1: line = (d)\nuse, l1\n")
    lat, _ = Reader().read(p)
    assert lat.reference.species.name == "positron"

    # caller overrides win
    lat, _ = Reader().read(p, species="electron", kinetic_energy_eV=5e6)
    assert lat.reference.species.name == "electron"
    assert lat.reference.kinetic_energy_eV == 5e6


def test_line_parameter_statements_set_the_reference(tmp_path):
    lat, _ = read_text(tmp_path, "d: drift, l=1\nl1: line = (d)\nuse, l1\n"
                                 "l1[e_tot] = 2738272000\nl1[beta_a] = 12\n")
    assert lat.reference.total_energy_eV == pytest.approx(2.738272e9)
    assert lat.meta["twiss"]["beta_a"] == 12.0


def test_expressions_variables_and_element_references(tmp_path):
    lat, _ = read_text(tmp_path, """
kq = 0.6
lq := 2 * 0.15
q1: quadrupole, l = lq, k1 = kq * sqrt(4) / 2
q2: quadrupole, l = q1[l], k1 = -q1[k1]
l1: line = (q1, q2)
use, l1
""")
    assert lat.variables["kq"].value == 0.6
    assert lat.variables["lq"].expression.text == "2 * 0.15"
    assert lat.elements["q1"].length == pytest.approx(0.3)
    assert lat.elements["q1"].multipole.Bn[1] == pytest.approx(0.6 * brho(lat))
    assert lat.elements["q2"].length == pytest.approx(0.3)
    assert lat.elements["q2"].multipole.Bn[1] == pytest.approx(-0.6 * brho(lat))


def test_call_is_resolved_relative_to_the_deck(tmp_path):
    (tmp_path / "sub").mkdir()
    (tmp_path / "sub" / "els.bmad").write_text("q1: quadrupole, l = 0.3, k1 = 0.6\n")
    lat, rep = read_text(tmp_path, 'call, file = "sub/els.bmad"\n'
                                   "d: drift, l = 1\nl1: line = (q1, d)\nuse, l1\n")
    assert isinstance(lat.elements["q1"], Quadrupole)
    assert lat.total_length == pytest.approx(1.3)
    # any prefix of FILENAME is legal Bmad
    lat, _ = read_text(tmp_path, 'call, f = "sub/els.bmad"\nl1: line = (q1)\nuse, l1\n',
                       name="deck2.bmad")
    assert "q1" in lat.elements


def test_missing_call_file_is_lossy_and_strict_raises(tmp_path):
    body = 'call, file = "nope.bmad"\nd: drift, l=1\nl1: line = (d)\nuse, l1\n'
    _, rep = read_text(tmp_path, body)
    assert "CALL_FILE_MISSING" in rep.codes()
    with pytest.raises(TranslationError):
        read_text(tmp_path, body, name="strict.bmad", strict=True)


def test_templates_and_attribute_overrides(tmp_path):
    lat, _ = read_text(tmp_path, """
q0: quadrupole, l = 0.6, k1 = 1, tilt
q1: q0, k1 = 2
q2: q0
l1: line = (q1, q2)
use, l1
q2[l] = 0.4
""")
    q1, q2 = lat.elements["q1"], lat.elements["q2"]
    assert isinstance(q1, Quadrupole) and isinstance(q2, Quadrupole)
    assert q1.length == pytest.approx(0.6)
    assert q1.multipole.Bn[1] == pytest.approx(2.0 * brho(lat))
    assert q2.multipole.Bn[1] == pytest.approx(1.0 * brho(lat))
    assert q2.length == pytest.approx(0.4)            # override applied after `use`
    # a bare `tilt` flag is Bmad's pi/(2(n+1)) default, inherited by both children
    assert q1.multipole.tilt[1] == pytest.approx(math.pi / 4)


def test_bare_tilt_defaults_per_order(tmp_path):
    lat, _ = read_text(tmp_path, """
q: quadrupole, l = 0.1, k1 = 1, tilt
s: sextupole, l = 0.1, k2 = 1, tilt
o: octupole, l = 0.1, k3 = 1, tilt
m: multipole, k1l = 1, t1, k3l = 2, t3
l1: line = (q, s, o, m)
use, l1
""")
    assert lat.elements["q"].multipole.tilt[1] == pytest.approx(math.pi / 4)
    assert lat.elements["s"].multipole.tilt[2] == pytest.approx(math.pi / 6)
    assert lat.elements["o"].multipole.tilt[3] == pytest.approx(math.pi / 8)
    # t1 = pi/4 makes the order-1 multipole purely skew
    m = lat.elements["m"]
    assert m.multipole.BnL.get(1, 0.0) == pytest.approx(0.0, abs=1e-12 * abs(brho(lat)))
    assert m.multipole.BsL[1] == pytest.approx(-1.0 * brho(lat))


# ---------------------------------------------------------------- lines
def test_nested_lines_with_reflection_and_repetition(tmp_path):
    lat, _ = read_text(tmp_path, """
a: drift, l = 1
b: drift, l = 2
c: marker
sub: line = (a, b)
main: line = (sub, -sub, 2*c, 3*(a, c))
use, main
""")
    names = [p.element.name for p in lat.flatten()]
    assert names == ["a", "b", "b", "a", "c", "c", "a", "c", "a", "c", "a", "c"]
    assert lat.total_length == pytest.approx(1 + 2 + 2 + 1 + 3 * 1)
    assert lat.lines["main"].items[1].reverse is True
    assert lat.lines["main"].items[2].repeat == 2


def test_use_selects_the_root_and_can_be_overridden(tmp_path):
    body = ("a: drift, l = 1\nb: drift, l = 2\n"
            "l1: line = (a)\nl2: line = (a, b)\nuse, l1\n")
    lat, _ = read_text(tmp_path, body)
    assert lat.use == "l1" and lat.total_length == pytest.approx(1.0)
    lat, _ = read_text(tmp_path, body, name="d2.bmad", use="l2")
    assert lat.use == "l2" and lat.total_length == pytest.approx(3.0)
    with pytest.raises(KeyError):
        read_text(tmp_path, body, name="d3.bmad", use="nope")


# ---------------------------------------------------------------- elements
def test_every_element_class(tmp_path):
    lat, rep = read_text(tmp_path, """
d: drift, l = 0.5
pp: pipe, l = 0.1
mon: monitor, l = 0.2
inst: instrument, l = 0.2
mk: marker
q: quadrupole, l = 0.6, k1 = 1
sx: sextupole, l = 0.6, k2 = 2
oc: octupole, l = 0.6, k3 = 3
mp: multipole, k1l = 0.02, k1sl = 0.03
ab: ab_multipole, b2 = 0.15, a1 = 0.03
bs: sbend, l = 0.8, angle = 0.08, e1 = 0.01, e2 = 0.02, fint = 0.5, hgap = 0.03, ref_tilt = 0.1
br: rbend, l = 0.8, angle = 0.08, e1 = 0.01, e2 = 0.02
sol: solenoid, l = 0.3, ks = 0.5
lc: lcavity, l = 0.5, voltage = 1e6, phi0 = -0.0833333333333333, rf_frequency = 325e6, n_cell = 1
hk: hkicker, l = 0.1, kick = 0.004
vk: vkicker, l = 0.1, kick = 0.005
kk: kicker, l = 0.1, hkick = 0.001, vkick = 0.002
rc: rcollimator, l = 0.1, x_limit = 0.02, y_limit = 0.03
ec: ecollimator, l = 0.1, x_limit = 0.02, y_limit = 0.03
fl: foil, material_type = "C", thickness = 1e-4, area_density = 0.237
ty: taylor, l = 0.5, {1: 0.5|1}, {2: 0.25|}
pa: patch, x_offset = 0.001, y_pitch = 0.002, tilt = 0.3
l1: line = (d, pp, mon, inst, mk, q, sx, oc, mp, ab, bs, br, sol, lc, hk, vk, kk, rc, ec, fl, ty, pa)
use, l1
""")
    e = lat.elements
    b = brho(lat)
    assert isinstance(e["d"], Drift) and isinstance(e["pp"], Drift)
    assert isinstance(e["mon"], Instrument) and e["mon"].family == "BPM"
    assert isinstance(e["inst"], Instrument) and e["inst"].family == "INSTRUMENT"
    assert isinstance(e["mk"], Marker)
    assert isinstance(e["q"], Quadrupole) and e["q"].multipole.Bn[1] == pytest.approx(1.0 * b)
    assert isinstance(e["sx"], Sextupole) and e["sx"].multipole.Bn[2] == pytest.approx(2.0 * b)
    assert isinstance(e["oc"], Octupole) and e["oc"].multipole.Bn[3] == pytest.approx(3.0 * b)
    # k{n}l / k{n}sl are exactly MAD-X's knl / ksl (verified engine-to-engine)
    assert isinstance(e["mp"], Multipole)
    assert e["mp"].multipole.BnL[1] == pytest.approx(0.02 * b)
    assert e["mp"].multipole.BsL[1] == pytest.approx(0.03 * b)
    # ab_multipole: b_n = k_nl / n!, a_n = k_nsl / n!  (measured with Tao)
    assert e["ab"].multipole.BnL[2] == pytest.approx(0.15 * 2 * b)
    assert e["ab"].multipole.BsL[1] == pytest.approx(0.03 * b)
    assert isinstance(e["bs"], Bend)
    assert e["bs"].length == pytest.approx(0.8)
    assert (e["bs"].bend.e1, e["bs"].bend.e2) == pytest.approx((0.01, 0.02))
    assert e["bs"].bend.edge_int1 == 0.5 and e["bs"].bend.edge_int2 is None
    assert e["bs"].bend.hgap == pytest.approx(0.03)
    assert e["bs"].bend.tilt_ref == pytest.approx(0.1)
    # rbend: `l` is the chord and Bmad shifts the pole faces by angle/2 itself
    assert e["br"].bend.rect is True
    assert e["br"].length == pytest.approx(0.8 * 0.04 / math.sin(0.04))
    assert (e["br"].bend.e1, e["br"].bend.e2) == pytest.approx((0.01 + 0.04, 0.02 + 0.04))
    assert isinstance(e["sol"], Solenoid) and e["sol"].solenoid.Bsol_T == pytest.approx(0.5 * b)
    assert isinstance(e["lc"], RFCavity)
    assert e["lc"].rf.voltage_V == 1e6
    assert e["lc"].rf.phase_rad == pytest.approx(-math.pi / 6)
    assert e["lc"].rf.frequency_Hz == 325e6 and e["lc"].rf.n_cell == 1
    assert isinstance(e["hk"], Kicker) and e["hk"].hkick == pytest.approx(0.004)
    assert e["vk"].vkick == pytest.approx(0.005)
    assert (e["kk"].hkick, e["kk"].vkick) == pytest.approx((0.001, 0.002))
    assert isinstance(e["rc"], Collimator) and e["rc"].aperture.shape == "RECTANGULAR"
    assert e["rc"].aperture.half_x == pytest.approx(0.02)
    assert e["ec"].aperture.shape == "ELLIPTICAL"       # Bmad's ecollimator default
    assert isinstance(e["fl"], Foil) and e["fl"].material == "C"
    assert e["fl"].thickness_kg_per_m2 == pytest.approx(0.237)
    assert isinstance(e["ty"], Taylor)
    assert e["ty"].matrix[0][0] == pytest.approx(0.5) and e["ty"].offset[1] == pytest.approx(0.25)
    assert isinstance(e["pa"], Patch)
    assert (e["pa"].x_offset, e["pa"].y_rot, e["pa"].tilt) == pytest.approx((0.001, 0.002, 0.3))
    assert rep.counts.get("DROPPED", 0) == 0


def test_bare_fint_flag_is_half(tmp_path):
    lat, _ = read_text(tmp_path, "b: sbend, l = 0.6, angle = 0.1, fint, hgap = 0.02\n"
                                 "l1: line = (b)\nuse, l1\n")
    assert lat.elements["b"].bend.edge_int1 == pytest.approx(0.5)
    assert lat.elements["b"].bend.edge_int2 is None     # Bmad's fintx defaults to fint


def test_rbend_with_g_uses_the_chord_relation(tmp_path):
    lat, _ = read_text(tmp_path, "b: rbend, l = 0.6, g = 0.01\nl1: line = (b)\nuse, l1\n")
    b = lat.elements["b"].bend
    assert b.angle == pytest.approx(2 * math.asin(0.01 * 0.6 / 2))
    assert lat.elements["b"].length == pytest.approx(b.angle / 0.01)


def test_rfcavity_is_a_ring_cavity(tmp_path):
    lat, rep = read_text(tmp_path, "r: rfcavity, l = 0.5, voltage = 1e6, phi0 = 0.1, "
                                   "rf_frequency = 325e6\nl1: line = (r)\nuse, l1\n")
    r = lat.elements["r"]
    assert isinstance(r, RFCavity)
    # Bmad's rfcavity uses -sin(2*pi*(phi_t - phi0)) where lcavity uses +cos: a reflection
    assert r.rf.phase_rad == pytest.approx(2 * math.pi * (0.25 - 0.1))
    assert r.rf.dE_ref_eV == 0.0
    assert "RING_RFCAVITY" in rep.codes()
    assert propagate(lat)[-1].ref_out.kinetic_energy_eV == \
        pytest.approx(lat.reference.kinetic_energy_eV)


def test_apertures_and_misalignments(tmp_path):
    lat, _ = read_text(tmp_path, """
q: quadrupole, l = 0.6, k1 = 1, x1_limit = 0.01, x2_limit = 0.02, y1_limit = 0.03,
   y2_limit = 0.04, aperture_type = elliptical, aperture_at = both_ends,
   x_offset = 1e-3, y_offset = 2e-3, z_offset = 3e-3, x_pitch = 1e-4, y_pitch = 2e-4
b: sbend, l = 0.6, angle = 0.1, roll = 0.05, ref_tilt = 0.2
d: drift, l = 0.1, tilt = 0.3, aperture = 0.05
l1: line = (q, b, d)
use, l1
""")
    q = lat.elements["q"]
    assert q.aperture.shape == "ELLIPTICAL" and q.aperture.aperture_at == "BOTH_ENDS"
    assert q.aperture.x_limits == pytest.approx((-0.01, 0.02))
    assert q.aperture.y_limits == pytest.approx((-0.03, 0.04))
    assert (q.shift.x_offset, q.shift.y_offset, q.shift.z_offset) == \
        pytest.approx((1e-3, 2e-3, 3e-3))
    assert (q.shift.x_rot, q.shift.y_rot) == pytest.approx((1e-4, 2e-4))
    assert q.shift.tilt == 0.0            # a quadrupole's tilt is multipole physics, not a shift
    b = lat.elements["b"]
    assert b.bend.tilt_ref == pytest.approx(0.2)     # geometry
    assert b.shift.tilt == pytest.approx(0.05)       # `roll` is the misalignment
    d = lat.elements["d"]
    assert d.shift.tilt == pytest.approx(0.3)
    assert d.aperture.x_limits == pytest.approx((-0.05, 0.05))


# ---------------------------------------------------------------- downgrades
def test_unsupported_type_is_dropped_in_both_regimes(tmp_path):
    body = ("bb: beambeam, sig_x = 1e-3\nd: drift, l=1\nl1: line = (d, bb)\nuse, l1\n")
    lat, rep = read_text(tmp_path, body)
    assert isinstance(lat.elements["bb"], Marker)
    assert lat.elements["bb"].native["bmad"]["type"] == "beambeam"
    assert "UNSUPPORTED_BMAD_TYPE" in rep.codes()
    with pytest.raises(TranslationError):
        read_text(tmp_path, body, name="s.bmad", strict=True)


@pytest.mark.parametrize("body, code, kind", [
    ("ov: overlay = {q1[k1]:1}, var = {k}\nq1: quadrupole, l=1, k1=1\n"
     "l1: line = (q1, ov)\nuse, l1\n", "BMAD_CONTROLLER", Directive),
    ("sq: sol_quad, l = 1, ks = 0.5, k1 = 0.2\nl1: line = (sq)\nuse, l1\n",
     "SOLQUAD_K1_DROPPED", Solenoid),
    ("ty: taylor, l = 0.5, {1: 0.5|12}\nl1: line = (ty)\nuse, l1\n",
     "TAYLOR_ORDER_TRUNCATED", Taylor),
    ("pa: patch, x_offset = 1e-3, t_offset = 1e-11\nl1: line = (pa)\nuse, l1\n",
     "PATCH_ATTR_DROPPED", Patch),
    ("bn: sbend, l = 0.6, g = 0.01, dg = -0.005\nl1: line = (bn)\nuse, l1\n",
     "BEND_ATTR_DROPPED", Bend),
])
def test_lossy_paths_in_both_regimes(tmp_path, body, code, kind):
    lat, rep = read_text(tmp_path, body)
    assert code in rep.codes()
    assert any(isinstance(el, kind) for el in lat.elements.values())
    with pytest.raises(TranslationError):
        read_text(tmp_path, body, name="strict.bmad", strict=True)


@pytest.mark.parametrize("body, code", [
    ("a: drift, l=1\nb: drift, l=2\nmix: list = (a, b)\nl1: line = (mix)\nuse, l1\n",
     "BMAD_LIST_AS_LINE"),
    ("a: drift, l=1\nmp: line[multipass] = (a, a)\nl1: line = (mp)\nuse, l1\n",
     "MULTIPASS_LINE"),
    ("q: quadrupole, l=1, k1=1, x1_limit=0.01, x2_limit=0.01, y1_limit=0.01, "
     "y2_limit=0.01, aperture_type = wall3d\nl1: line = (q)\nuse, l1\n",
     "APERTURE_TYPE_UNSUPPORTED"),
])
def test_more_lossy_paths_in_both_regimes(tmp_path, body, code):
    _, rep = read_text(tmp_path, body)
    assert code in rep.codes()
    with pytest.raises(TranslationError):
        read_text(tmp_path, body, name="strict.bmad", strict=True)


def test_non_positive_reference_energy_is_clamped(tmp_path):
    p = tmp_path / "bad.bmad"
    p.write_text("parameter[particle] = proton\nparameter[e_tot] = 1e6\n"
                 "d: drift, l=1\nl1: line = (d)\nuse, l1\n")
    lat, rep = Reader().read(p)
    assert "REFERENCE_ENERGY_INVALID" in rep.codes()
    assert lat.reference.kinetic_energy_eV == 1.0
    with pytest.raises(TranslationError):
        Reader().read(p, strict=True)


def test_equivalent_paths_do_not_raise_in_strict_mode(tmp_path):
    """EQUIVALENT is not a problem: only LOSSY/DROPPED stop a strict conversion."""
    lat, rep = read_text(tmp_path, "e: elseparator, l = 1, hkick = 0.005, gap = 0.11\n"
                                   "l1: line = (e)\nuse, l1\n", strict=True)
    assert "ELSEPARATOR_AS_KICKER" in rep.codes()
    assert lat.elements["e"].electric is True


def test_em_field_becomes_a_fieldmap_with_its_files(tmp_path):
    lat, rep = read_text(tmp_path, """
em: em_field, l = 1.4, field_calc = fieldmap,
    grid_field = {geometry = xyz, field_type = magnetic, file = "map3d.h5"}
l1: line = (em)
use, l1
""")
    em = lat.elements["em"]
    assert isinstance(em, FieldMap)
    assert em.files == ["map3d.h5"]
    assert "grid_field" in em.native["bmad"]
    assert "BMAD_GRID_FIELD" in rep.codes()


def test_call_colon_colon_pulls_in_an_attribute_fragment(tmp_path):
    (tmp_path / "frag.bmad").write_text("field_calc = fieldmap,\n"
                                        'grid_field = {file = "g.h5"}\n')
    lat, _ = read_text(tmp_path, "em: em_field, l = 1.4, call::frag.bmad\n"
                                 "l1: line = (em)\nuse, l1\n")
    assert lat.elements["em"].files == ["g.h5"]


# ---------------------------------------------------------------- superimpose
def test_superimpose_of_a_thin_element_is_resolved(tmp_path):
    lat, rep = read_text(tmp_path, """
d1: drift, l = 1.0
q1: quadrupole, l = 0.2, k1 = 0.5
mk: marker, superimpose, ref = q1, offset = 0.3
l1: line = (d1, q1, d1)
use, l1
""")
    placed = lat.flatten()
    names = [p.element.name for p in placed]
    assert "mk" in names
    i = names.index("mk")
    assert placed[i].s_in == pytest.approx(1.4)          # q1 centre 1.1 + 0.3
    assert lat.total_length == pytest.approx(2.2)
    assert "SUPERIMPOSE_RESOLVED" in rep.codes()


def test_superimpose_of_a_thick_element_splits_a_drift(tmp_path):
    lat, rep = read_text(tmp_path, """
d1: drift, l = 1.0
q1: quadrupole, l = 0.2, k1 = 0.5
mp: monitor, l = 0.1, superimpose, ref = q1, offset = 0.4
l1: line = (d1, q1, d1)
use, l1
""")
    placed = lat.flatten()
    names = [p.element.name for p in placed]
    assert "mp" in names
    assert placed[names.index("mp")].s_in == pytest.approx(1.45)
    assert lat.total_length == pytest.approx(2.2)
    assert "SUPERIMPOSE_RESOLVED" in rep.codes()


def test_superimpose_over_a_magnet_is_lossy(tmp_path):
    body = """
d1: drift, l = 1.0
q1: quadrupole, l = 0.2, k1 = 0.5
mp: monitor, l = 0.1, superimpose, ref = q1, offset = 0
l1: line = (d1, q1, d1)
use, l1
"""
    lat, rep = read_text(tmp_path, body)
    assert "SUPERIMPOSE_UNSUPPORTED" in rep.codes()
    assert "mp" not in [p.element.name for p in lat.flatten()]
    assert lat.elements["mp"].native["bmad"]["superimpose"]["ref"] == "q1"
    with pytest.raises(TranslationError):
        read_text(tmp_path, body, name="strict.bmad", strict=True)


# ---------------------------------------------------------------- energy walk
def test_local_rigidity_is_used_through_an_lcavity(tmp_path):
    """Bmad's reference energy follows lcavity, so k1 must be converted locally."""
    lat, _ = read_text(tmp_path, """
q1: quadrupole, l = 0.1, k1 = 1
c1: lcavity, l = 0.5, voltage = 5e8, phi0 = 0, rf_frequency = 325e6
q2: quadrupole, l = 0.1, k1 = 1
l1: line = (q1, c1, q2)
use, l1
""")
    walk = propagate(lat)
    assert walk[-1].ref_out.kinetic_energy_eV == \
        pytest.approx(lat.reference.kinetic_energy_eV + 5e8)
    b_in = walk[0].ref_in.brho_signed
    b_out = walk[2].ref_in.brho_signed
    assert b_out > b_in
    assert lat.elements["q1"].multipole.Bn[1] == pytest.approx(b_in)
    assert lat.elements["q2"].multipole.Bn[1] == pytest.approx(b_out)


def test_reused_definition_at_two_energies_is_recorded(tmp_path):
    _, rep = read_text(tmp_path, """
q1: quadrupole, l = 0.1, k1 = 1
c1: lcavity, l = 0.5, voltage = 5e8, phi0 = 0, rf_frequency = 325e6
l1: line = (q1, c1, q1)
use, l1
""")
    assert "MULTI_RIGIDITY_DEFINITION" in rep.codes()


# ---------------------------------------------------------------- real deck
@pytest.mark.skipif(not FOREIGN.is_file(),
                    reason=f"Bmad clone absent (GPL-3, never vendored): {FOREIGN}")
def test_bmad_own_regression_deck_parses():
    """Bmad's ``write_foreign_test.bmad`` is the canonical one-of-everything deck."""
    lat, rep = Reader().read(FOREIGN)
    placed = lat.flatten()
    assert len(lat.elements) == 61
    assert len(placed) == 51
    assert lat.total_length == pytest.approx(94.80000180000728)
    assert lat.reference.species.name == "positron"      # Bmad's default particle
    kinds = {p.element.kind for p in placed}
    assert {"Bend", "Quadrupole", "Sextupole", "Octupole", "Multipole", "Solenoid",
            "RFCavity", "Kicker", "Collimator", "Instrument", "Marker", "Taylor",
            "Patch", "FieldMap"} <= kinds
    codes = rep.codes()
    for code in ("UNSUPPORTED_BMAD_TYPE", "RING_RFCAVITY", "BMAD_GRID_FIELD",
                 "SOLQUAD_K1_DROPPED", "TAYLOR_ORDER_TRUNCATED", "ELSEPARATOR_AS_KICKER"):
        assert code in codes, code
    # the deck exercises inheritance (q0 -> quadrupole1..5, sb0/rb0 -> sbend1..7),
    # an inline `call::gg.bmad`, a ~90-term taylor and a 19-character element name
    assert lat.elements["quadrupole1"].kind == "Quadrupole"
    assert lat.elements["em_field1"].kind == "FieldMap"
    assert "ac_kicker0123456789" in lat.elements
    assert len(rep.entries) == len(lat.elements), "one ledger entry per source element"
