#!/usr/bin/env python3
# lattix <version> from <fmt>
"""ImpactX lattice generated by lattix.

Strengths are normalized with the SIGNED rigidity at each element's entrance
(energy_mode='local'), which is the rigidity ImpactX itself carries there.
Add a beam distribution and call sim.track_particles() to run.
"""
from impactx import ImpactX, elements
import amrex.space3d as amr


def _map6(rows):
    """6x6 transport matrix for elements.LinearMap (1-indexed)."""
    m = amr.SmallMatrix_6x6_F_SI1_double()
    base = getattr(m, "starting_index", 1)
    for i, row in enumerate(rows, start=base):
        for j, v in enumerate(row, start=base):
            m[i, j] = v
    return m


sim = ImpactX()
sim.particle_shape = 2
sim.space_charge = False
sim.slice_step_diagnostics = False
sim.init_grids()

# --- reference particle: proton, 100 MeV kinetic
ref = sim.particle_container().ref_particle()
ref.set_charge_qe(1)
ref.set_mass_MeV(938.27208816)
ref.set_kin_energy_MeV(100)

# --- lattice (36 elements, default nslice = 1)
lattice = elements.KnownElementsList()
lattice.append(elements.Drift(name="dr", ds=0.4, nslice=1))
lattice.append(elements.Quad(name="qp", ds=0.3, k=0.6, rotation=1.14591559026165, nslice=1))
lattice.append(elements.Drift(name="sx_in", ds=0.1, nslice=1))
lattice.append(elements.Multipole(name="sx", multipole=3, k_normal=0.3, k_skew=0))
lattice.append(elements.Drift(name="sx_out", ds=0.1, nslice=1))
lattice.append(elements.Drift(name="oc_in", ds=0.1, nslice=1))
lattice.append(elements.Multipole(name="oc", multipole=4, k_normal=0.5, k_skew=0))
lattice.append(elements.Drift(name="oc_out", ds=0.1, nslice=1))
lattice.append(elements.Multipole(name="mp_m1", multipole=1, k_normal=0.01, k_skew=0))
lattice.append(elements.Multipole(name="mp_m2", multipole=2, k_normal=0, k_skew=0.03))
lattice.append(elements.Multipole(name="mp_m3", multipole=3, k_normal=0.3, k_skew=0))
lattice.append(elements.DipEdge(name="bd_e1", psi=0.02, rc=10, g=0.06, K2=0.45, location="entry", rotation=5.72957795130823))
lattice.append(elements.Sbend(name="bd", ds=1, rc=10, rotation=5.72957795130823, nslice=1))
lattice.append(elements.DipEdge(name="bd_e2", psi=0.03, rc=10, g=0.06, K2=0.5, location="exit", rotation=5.72957795130823))
lattice.append(elements.Sol(name="sl", ds=0.4, ks=0.3, nslice=1))
lattice.append(elements.Drift(name="cv_in", ds=0.25, nslice=1))
lattice.append(elements.ShortRF(name="cv_rf", V=0.0021315778495789, freq=325000000, phase=-30))
lattice.append(elements.Drift(name="cv_out", ds=0.25, nslice=1))
lattice.append(elements.Drift(name="fm_in", ds=0.3, nslice=1))
lattice.append(elements.ShortRF(name="fm_rf", V=0.00184600056787954, freq=325000000, phase=-30))
lattice.append(elements.Drift(name="fm_out", ds=0.3, nslice=1))
lattice.append(elements.Drift(name="nc", ds=0.7, nslice=1))
lattice.append(elements.Drift(name="rq", ds=0.05, nslice=1))
lattice.append(elements.Drift(name="kk_in", ds=0.05, nslice=1))
lattice.append(elements.Kicker(name="kk_k", xkick=0.001, ykick=-0.002, unit="dimensionless"))
lattice.append(elements.Drift(name="kk_out", ds=0.05, nslice=1))
lattice.append(elements.Drift(name="cl_in", ds=0.05, nslice=1))
lattice.append(elements.Aperture(name="cl_ap", aperture_x=0.02, aperture_y=0.03, shape="elliptical", action="absorb"))
lattice.append(elements.Drift(name="cl_out", ds=0.05, nslice=1))
lattice.append(elements.Marker(name="mk"))
lattice.append(elements.Marker(name="bp"))
lattice.append(elements.Marker(name="fl"))
lattice.append(elements.LinearMap(name="ty", ds=0.2, R=_map6([[1, 0.5, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 1, 0.25], [0, 0, 0, 0, 0, 1]])))
lattice.append(elements.Marker(name="pt"))
lattice.append(elements.Marker(name="rc"))
lattice.append(elements.Drift(name="sup_child", ds=0.2, nslice=1))

sim.lattice.extend(lattice)

# dropped directive dv: ADJUST 1 2

# sim.track_particles()   # add a beam distribution first
# sim.finalize()
