#!/usr/bin/env python3
# lattix <version> from <fmt>
"""ImpactX lattice generated by lattix.

Strengths are normalized with the SIGNED rigidity at each element's entrance
(energy_mode='local'), which is the rigidity ImpactX itself carries there.
Add a beam distribution and call sim.track_particles() to run.
"""
from impactx import ImpactX, elements

sim = ImpactX()
sim.particle_shape = 2
sim.space_charge = False
sim.slice_step_diagnostics = False
sim.init_grids()

# --- reference particle: proton, 800 MeV kinetic
ref = sim.particle_container().ref_particle()
ref.set_charge_qe(1)
ref.set_mass_MeV(938.27208816)
ref.set_kin_energy_MeV(800)

# --- lattice (20 elements, default nslice = 1)
lattice = elements.KnownElementsList()
lattice.append(elements.Quad(name="QF", ds=0.3, k=0.6, nslice=1))
lattice.append(elements.Drift(name="D1", ds=0.5, nslice=1))
lattice.append(elements.DipEdge(name="B1_e1", psi=0.05, rc=10, g=0.04, K2=0.5, location="entry"))
lattice.append(elements.Sbend(name="B1", ds=1, rc=10, nslice=1))
lattice.append(elements.DipEdge(name="B1_e2", psi=0.05, rc=10, g=0.04, K2=0.5, location="exit"))
lattice.append(elements.Drift(name="D2", ds=0.5, nslice=1))
lattice.append(elements.Sol(name="SOL", ds=0.4, ks=0.3, nslice=1))
lattice.append(elements.Drift(name="D3", ds=0.2, nslice=1))
lattice.append(elements.ShortRF(name="CAV", V=0.00106578892478945, freq=325000000, phase=-30))
lattice.append(elements.Drift(name="D4", ds=0.2, nslice=1))
lattice.append(elements.Kicker(name="COR", xkick=0.001, ykick=-0.002, unit="dimensionless"))
lattice.append(elements.Drift(name="D5", ds=0.3, nslice=1))
lattice.append(elements.Aperture(name="COLL", aperture_x=0.02, aperture_y=0.03, shape="rectangular", action="absorb"))
lattice.append(elements.Drift(name="D6", ds=0.5, nslice=1))
lattice.append(elements.DipEdge(name="B2_e1", psi=-0.05, rc=-10, g=0, K2=0, location="entry"))
lattice.append(elements.Sbend(name="B2", ds=1, rc=-10, nslice=1))
lattice.append(elements.DipEdge(name="B2_e2", psi=-0.05, rc=-10, g=0, K2=0, location="exit"))
lattice.append(elements.Drift(name="D7", ds=0.5, nslice=1))
lattice.append(elements.Quad(name="QD", ds=0.3, k=-0.599578511631037, nslice=1))
lattice.append(elements.Marker(name="END"))

sim.lattice.extend(lattice)


# sim.track_particles()   # add a beam distribution first
# sim.finalize()
