#!/usr/bin/env python3
# lattix <version> from <fmt>
"""ImpactX lattice generated by lattix.

Strengths are normalized with the SIGNED rigidity at each element's entrance
(energy_mode='local'), which is the rigidity ImpactX itself carries there.
Add a beam distribution and call sim.track_particles() to run.
"""
from impactx import ImpactX, elements

sim = ImpactX()
sim.particle_shape = 2
sim.space_charge = False
sim.slice_step_diagnostics = False
sim.init_grids()

# --- reference particle: proton, 799.99991184 MeV kinetic
ref = sim.particle_container().ref_particle()
ref.set_charge_qe(1)
ref.set_mass_MeV(938.27208816)
ref.set_kin_energy_MeV(799.99991184)

# --- lattice (13 elements, default nslice = 1)
lattice = elements.KnownElementsList()
lattice.append(elements.Quad(name="qf", ds=0.3, k=0.6, nslice=1))
lattice.append(elements.Drift(name="drift_0", ds=0.7, nslice=1))
lattice.append(elements.DipEdge(name="b1_e1", psi=0.05, rc=10, g=0, K2=0, location="entry"))
lattice.append(elements.Sbend(name="b1", ds=1, rc=10, nslice=1))
lattice.append(elements.DipEdge(name="b1_e2", psi=0.05, rc=10, g=0, K2=0, location="exit"))
lattice.append(elements.Drift(name="drift_1", ds=1, nslice=1))
lattice.append(elements.Quad(name="qd", ds=0.3, k=-0.6, nslice=1))
lattice.append(elements.Drift(name="drift_2", ds=1, nslice=1))
lattice.append(elements.DipEdge(name="b1_e1", psi=0.05, rc=10, g=0, K2=0, location="entry"))
lattice.append(elements.Sbend(name="b1", ds=1, rc=10, nslice=1))
lattice.append(elements.DipEdge(name="b1_e2", psi=0.05, rc=10, g=0, K2=0, location="exit"))
lattice.append(elements.Drift(name="drift_3", ds=1.3, nslice=1))
lattice.append(elements.Marker(name="m1"))

sim.lattice.extend(lattice)


# sim.track_particles()   # add a beam distribution first
# sim.finalize()
