#!/usr/bin/env python3
# lattix <version> from <fmt>
"""ImpactX lattice generated by lattix.

Strengths are normalized with the SIGNED rigidity at each element's entrance
(energy_mode='local'), which is the rigidity ImpactX itself carries there.
Add a beam distribution and call sim.track_particles() to run.
"""
from impactx import ImpactX, elements

sim = ImpactX()
sim.particle_shape = 2
sim.space_charge = False
sim.slice_step_diagnostics = False
sim.init_grids()

# --- reference particle: proton, 2.1 MeV kinetic
ref = sim.particle_container().ref_particle()
ref.set_charge_qe(1)
ref.set_mass_MeV(938.27208816)
ref.set_kin_energy_MeV(2.1)

# --- lattice (12 elements, default nslice = 1)
lattice = elements.KnownElementsList()
lattice.append(elements.Quad(name="q1", ds=0.1, k=5, nslice=1))
lattice.append(elements.Drift(name="da1", ds=0.2, nslice=1))
lattice.append(elements.ShortRF(name="cav1", V=0.000319736677436836, freq=162500000, phase=-30))
lattice.append(elements.Drift(name="db1", ds=0.2, nslice=1))
lattice.append(elements.Quad(name="q2", ds=0.1, k=-4.71640752547624, nslice=1))
lattice.append(elements.Drift(name="da2", ds=0.2, nslice=1))
lattice.append(elements.ShortRF(name="cav2", V=0.000319736677436836, freq=162500000, phase=-30))
lattice.append(elements.Drift(name="db2", ds=0.2, nslice=1))
lattice.append(elements.Quad(name="q3", ds=0.1, k=4.47611096922601, nslice=1))
lattice.append(elements.Drift(name="da3", ds=0.2, nslice=1))
lattice.append(elements.ShortRF(name="cav3", V=0.000319736677436836, freq=162500000, phase=-30))
lattice.append(elements.Drift(name="db3", ds=0.2, nslice=1))

sim.lattice.extend(lattice)


# sim.track_particles()   # add a beam distribution first
# sim.finalize()
